### ISSUE TITLE
sharp comments

### ISSUE THREAD

**Issue by bbcVld** [jwortmann/ini-syntax#7]
Is there the way to add sharp comment (# ...) to ctrl + / ?
Or add it to group comment (ctrl + shift + /)?

**Comment by jwortmann** [comment]
The symbol for the `toggle_comment` functionality is defined by the value for `TM_COMMENT_START` in the file [Comments.tmPreferences](https://github.com/jwortmann/ini-syntax/blob/master/Comments.tmPreferences#L16).
I think the easiest way to adjust this, would be to create a local override for this file and replace `;` by `#` in line 16. To create such an override, you need to go to the Packages directory (Preferences > Browse Packages...), create a new folder `INI` and copy the  adjusted file into that folder.

Perhaps it might be useful to introduce a setting in a `.sublime-settings` file for it to easily allow this configuration, but I'm not sure if that would even be possible.

**Comment by bbcVld** [comment]
@jwortmann , this helps, thanks!

I played with this file and want to say:
1. group comments does not work as single one. So it can't helps.
2. If you add key TM_COMMENT_START_2 with '# ' value it's able to uncomment this comment type.

I don't know how to cycle comments type or transform from single to group or vice versa.
Anyway, it would be nice but not necessary. I think this issue can be closed.

**Comment by jwortmann** [comment]
Thanks for the suggestion. I tested it and can confirm everything you wrote.

While adding `TM_COMMENT_START_2` allows to uncomment `#`-style comments, `;` is still used when a comment is added, even with the group/block-comment keybinding <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>/</kbd>. Therefore I'm not sure if this would be very helpful, because this behavior would still be incomplete and confusing. Since there exist no special block comments in INI or related files (afaik), I agree that it might be nice to use this keybinding for `#`-style line comments instead, if it would work as desired.

I don't think that it's easily possible, but I can imagine a way how this could theoretically be implemented. It would require some "hacks" to override the default `toggle_comment` functionality for INI files though:
In the default keybindings (Windows + Linux) there is defined
```json
	{ "keys": ["ctrl+/"], "command": "toggle_comment", "args": { "block": false } },
	{ "keys": ["ctrl+shift+/"], "command": "toggle_comment", "args": { "block": true } },
```
The whole `toggle_comment` logic is defined in the file `comment.py` which ships with ST and can be opened via `View Package File: Default/comment.py` from the command palette. In particular, the `run` method from the `ToggleCommentCommand` class is invoked when this keybinding is pressed. It would be possible to replace this `toggle_comment` functionality only for INI files, for example by a keybinding like this:
```json
	{ "keys": ["ctrl+shift+/"], "command": "toggle_comment_ini", "context": [{ "key": "selector", "operand": "source.ini" }] },
```
and then reimplement this functionality as a new `toggle_comment_ini` command, which uses line comments, but start with `# `.

However, this would only work if a user has not defined another keybinding for the block comments. So I'm not sure if it is worth to implement this or maybe would even cause other issues. Therefore I guess I will leave it for now, and hope that the way to override the `Comments.tmPreferences` file as described above is sufficient, if someone prefers `#` instead of `;` for the `toggle_comment` functionality.

**Comment by jwortmann** [comment]
I added the `TM_COMMENT_START_2` setting with `#` to be able to uncomment those comments with the default keybinding. I still can't think of a good way to allow to toggle comments with both `;` and `#` at the same time.

Maybe we can leave this issue open, so that people who want to use the toggle_comment functionality with the `#` symbol by default can easily find how to modify the settings to achieve this behavior, as explained above.

**Comment by bbcVld** [comment]
>  I still can't think of a good way to allow to toggle comments

Now I think that it will be better a separate plugin which does not overload existing functions but add some new.
A separate plugin because it can be other languages (schemas) with multi comments and some other functionality.
